version: "3.7"
services:
  esyploynginx:
    build:
      args:
        version: ${NGINX_TAG}
      context: .
      dockerfile: ./docker-compose/nginx/Dockerfile
    container_name: "${PROJECT_NAME}-nginx"
    restart: unless-stopped
    volumes:
      - ./site:/var/www/html
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.easyploy.rule=Host(`${BASE_URL}`)
      - traefik.http.routers.easyploy.tls=true
      - traefik.http.routers.easyploy.tls.certresolver=le
      - traefik.http.routers.easyploy.entrypoints=websecure
      - traefik.http.middlewares.easyploy-redirect-web-secure.redirectscheme.scheme=https
      - traefik.http.routers.easyploy-web.middlewares=easyploy-redirect-web-secure
      - traefik.http.routers.easyploy-web.rule=Host(`${BASE_URL}`)
      - traefik.http.routers.easyploy-web.entrypoints=web
networks:
  proxy:
    external:
      name: global_network
